#!/bin/bash
# This will build the static files so they can be served directly with Caddy in the prod deploy.
# This should be called with `docker compose exec app /app/build_static`.
set -e
# build js files
yarn --cwd /app/frontend build
# purge existing static volume
if [ "$1" == "--keep" ]; then
  shift
else
  rm -rf /build/backend/*
fi
# collect static files
/app/backend/manage.py collectstatic --noinput
# build extension
/app/build_extension "$@"
