# Generated by Django 3.1.8 on 2021-11-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0006_huntconfig_enable_discord_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="is_placeholder",
            field=models.BooleanField(
                default=False,
                help_text="Used as a placeholder for information before the puzzle is released.",
            ),
        ),
    ]
