# Generated by Django 3.1.14 on 2023-09-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_botconfig_login_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('uid', models.CharField(max_length=500)),
                ('scopes', models.CharField(help_text='List of Google OAuth scopes', max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('access_token', models.CharField(max_length=500)),
                ('expires_at', models.BigIntegerField(help_text='Unix timestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
