# Generated by Django 3.1.14 on 2025-01-17 19:35

import autoslug.fields
from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0011_huntconfig_block_metas_on_feeders'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='alert_locked_puzzle_webhook',
            field=models.CharField(blank=True, default='', help_text='Discord webhook for new locked puzzle alerts.', max_length=500),
        ),
        migrations.CreateModel(
            name='LockedPuzzle',
            fields=[
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=500, populate_from='name', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, default='', help_text='Can be path relative to hunt root', max_length=500)),
                ('original_link', models.CharField(blank=True, default='', editable=False, help_text='Link upon creation. (Used to ensure scraper does not duplicate)', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('hidden', models.BooleanField(default=False, help_text='Hidden objects will not be shown.')),
                ('notes', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(default=dict, help_text='Keys with optional values.')),
                ('discord_text_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('discord_voice_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('sheet_link', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lockedpuzzle_created_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lockedpuzzle_modified_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
