# Generated by Django 5.2.9 on 2025-12-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0013_default_bigautofield"),
    ]

    operations = [
        migrations.AddField(
            model_name="huntconfig",
            name="create_voice_channels_by_default",
            field=models.BooleanField(
                default=False,
                help_text="Create voice channels for new puzzles when scraping and default for manual puzzle creation.",
            ),
        ),
    ]
