#!/usr/bin/env bash
set -e
REAL_SOURCE="$(perl -e "use Cwd 'abs_path'; print abs_path('${BASH_SOURCE}')")"
cd "$(dirname "$(dirname "${REAL_SOURCE}")")"

DOCKER_COMPOSE_COMMAND=(
  command
  docker compose
  -f docker-compose.yml
)
if [ "$1" = "--localhost" ]; then
  DOCKER_COMPOSE_COMMAND+=(-f docker-compose.prod.localhost.yml)
else
  DOCKER_COMPOSE_COMMAND+=(-f docker-compose.prod.yml)
fi
DOCKER_COMPOSE_COMMAND+=(
  --env-file prod.default.env
)
if [ -f prod.override.env ]; then
  DOCKER_COMPOSE_COMMAND+=(
    --env-file prod.override.env
  )
fi

docker-compose() {
  "${DOCKER_COMPOSE_COMMAND[@]}" "$@"
}

docker-compose build
mkdir -p frontend/node_modules
docker-compose up -d
docker-compose exec app /app/build_static
# command needs to be run with --sign to create a new Firefox version
docker-compose exec app /app/build_extension # --sign
docker-compose exec app /app/backend/manage.py migrate
docker-compose restart app
docker-compose exec app /app/backend/manage.py check
