#!/usr/bin/env bash
set -e
REAL_SOURCE="$(perl -e "use Cwd 'abs_path'; print abs_path('${BASH_SOURCE}')")"
cd "$(dirname "$(dirname "${REAL_SOURCE}")")"

docker-compose() {
  command docker compose -f docker-compose.yml -f docker-compose.dev.yml "$@"
}

docker-compose build
mkdir -p frontend/node_modules
docker-compose up -d
docker-compose exec app /app/backend/manage.py migrate
docker-compose exec app /app/backend/manage.py check
