#!/usr/bin/env bash
set -e
REAL_SOURCE="$(perl -e "use Cwd 'abs_path'; print abs_path('${BASH_SOURCE}')")"
cd "$(dirname "$(dirname "${REAL_SOURCE}")")"

if $(docker compose exec app bash -c '[[ "$BUILD_MODE" == dev ]]')
then
  docker compose exec -u "$(id -u):$(id -g)" app /app/backend/manage.py makemigrations
else
  >&2 echo Error: Is the dev environment running?
  exit 1
fi
