#!/usr/bin/env bash
set -e
REAL_SOURCE="$(perl -e "use Cwd 'abs_path'; print abs_path('${BASH_SOURCE}')")"
cd "$(dirname "$(dirname "${REAL_SOURCE}")")"

if docker inspect checkmate-app &>/dev/null
then
  docker run --rm -it -v "$(pwd)/frontend:/host" -u "$(id -u):$(id -g)" -w /host checkmate-app yarn install --non-interactive --modules-folder /tmp/node_modules
else
  >&2 echo 'Error: First run `./scripts/initialize_dev` to build the image (may need to revert the package.json first)'
  exit 1
fi
